Repair accessToken Sepehr driver & translateStatus for Sadad driver
shetabit/multipay pull request #266
Opened 2024-09-02 17:37 UTC by xfire5000

حل مشکل دریافت توکن در درگاه بانک صادرات و افزودن دو کد خطا برای درگاه سداد

2024-09-08 19:39 UTC, khanzadimahdi requested changes

2024-09-08 19:39 UTC, khanzadimahdi commented on src/Drivers/Sepehr/Sepehr.php
> +use Illuminate\Support\Facades\Cache;
این پکیج pure php هست و لاراولی نیست! اجازه استفاده از پکیج های لاراولی رو ندارید!

2024-09-08 19:41 UTC, xfire5000 commented
بله با session حل خواهد شد

2024-09-08 19:42 UTC, khanzadimahdi commented on src/Drivers/Sepehr/Sepehr.php
> +        Cache::put('accessToken', $access_token, now()->addMinute());
اینکار درست نیست! اولا از پکیج لاراول نمیتونید استفاده کنید. دوما اگه از درایور غیر session استفاده بشه اون موقع یک یوزر میتونه اکسز توکن یوزر دیگه رو استفاده کنه یا overwrite کنه.

2024-09-08 19:43 UTC, khanzadimahdi commented on src/Drivers/Sepehr/Sepehr.php
> -            'token' => $this->invoice->getTransactionId(),
شما باید از transactionId در صورت موجود بودن استفاده کنید و اگه موجود نبود میتونید مقدار مورد نظر خودتون رو پاس بدید بهش. اما درستش اینه که توی purchase ترنزکشن نامبر رو ست کنید و موقع pay یا verify ازش استفاده کنید.

2024-09-08 19:47 UTC, khanzadimahdi commented
> بله با session حل خواهد شد

از session هم نباید استفاده کنید چون این پکیج ممکنه برای restful API استفاده بشه و سشن فعال نباشه!

2025-02-20 11:53 UTC, khanzadimahdi commented
وقت بخیر. در صورتی که مشکلات این PR رفع نشه باید اونو ببندم. ممنونم ازتون.

2025-02-28 08:14 UTC, closed without merging